version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: db
    volumes:
      - dbasy-mysql-v:/var/lib/mysql

volumes:
  dbasy-mysql-v: